### ISSUE TITLE
SQUIM_OBJECTIVE not in torchaudio 2.0.2

### ISSUE THREAD

**Issue by dreamk73** [constructor-tech/attest-speech-analysis-tool#2]
I have installed a clean version of the code on MacOS and installed the packages in the requirements file.

Now when I run python run.py ui I get the following error:

cannot import name 'SQUIM_OBJECTIVE' from 'torchaudio.pipelines' (/Users/esther/miniconda3/envs/attest/lib/python3.10/site-packages/torchaudio/pipelines/__init__.py)

According to the requirements file it is installing torchaudio 2.0.2 and I have verified that that is the version that is installed in my conda environment. But it doesn't mention SQUIM_OBJECTIVE in the __init__.py file. 

I solved it by uninstalling torchaudio 2.0.2 and installing torchaudio 2.2.2 (which also updated torch from 2.0.1 to 2.2.2).

**Comment by dmitrii-obukhov** [comment]
@dreamk73  Thank you for reporting this bug!

Indeed, the version of torchaudio (and PyTorch as well) should be at least 2.1.0. 

The requirements file has been updated accordingly.

**Comment by dmitrii-obukhov** [comment]
Fixed in 517ec2c7a0ce7eff59d99a603241b446059e45ac
